config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @item = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @list = List.find(params[:item][:list_id])
    @item = @list.items.new(item_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

private
  def item_params
    params.require(:item).permit(:name, :complete)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.all
  end

  def show
    @list = List.find(params[:id])
    @item = @list.items.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
     @list.destroy
    redirect_to lists_path
  end

private
  def list_params
    params.require(:list).permit(:thing, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :complete %>
<%= f.check_box :complete %>
<br />

<%= f.submit %>

<% end %>

<%= link_to 'Back', items_path %>

app/views/items/edit.html.erb
<h1>Editing: <%= @item.name %> </h1>
<hr />

<%= render(partial: 'form') %>

app/views/items/index.html.erb
<h1> Items list </h1>
<hr />

<ol>
  <% @item.each do |item| %>
    <li>
      <%= item.name %>
      <!-- <%= link_to 'Items', item_path(item) %> - -->
      <%= link_to 'Edit', edit_item_path(item) %> -
      <%= link_to 'Delete', item_path(item), method: :delete, data: {confirm: 'Dlete this?'} %>
    </li>
  <% end %>
</ol>

<%= link_to 'Add Items', new_item_path %> <br />
<%= link_to 'Main Lists', lists_path %>

app/views/items/new.html.erb
<h1> Add to your list </h1>
<hr />

<%= render(partial: 'form') %>

app/views/items/show.html.erb
<h1> Items </h1>
<hr />

<%= @item.name %>
<%= @item.complete %>
<br />
<br />

<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondTodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>

<%= f.label :thing %>
<%= f.text_field :thing %>

<%= f.label :completed %>
<%= f.check_box :completed %>
<br />

<%= f.submit %>

<% end %>

<%= link_to 'Back', lists_path %>

app/views/lists/edit.html.erb
<h1>Editing: <%= @list.thing %> </h1>
<hr />

<%= render(partial: 'form') %>

app/views/lists/index.html.erb
<h1> Todo list </h1>
<hr />

<ul>
  <% @list.each do |list| %>
    <li>
      <%= list.thing %>
      <%= link_to 'Items', list_path(list) %> -
      <%= link_to 'Edit', edit_list_path(list) %> -
      <%= link_to 'Delete', list_path(list), method: :delete, data: {confirm: 'Dlete this?'} %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add to List', new_list_path %>

app/views/lists/new.html.erb
<h1> Add to your list </h1>
<hr />

<%= render(partial: 'form') %>

app/views/lists/show.html.erb
<h1> List of Items </h1>
<hr />

<%  @list.items.each do |item| %>
  <%= item.name %>
  <!-- <%= link_to 'Edit', edit_item_path %>   change to links to other places -->
  <%= link_to 'Delete', item_path, method: :delete %> <!-- can't delete from this -->
  <br />
<% end %>

<%= form_for @item do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :complete %>
<%= f.check_box :complete %>
<br />

<%= f.hidden_field :list_id, :value => @list.id %>

<%= f.submit %>

<% end %>

<br />
<br />
<%= link_to 'Back', lists_path %>